csitdjango/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import *
from django.conf import settings
from django.conf.urls.static import static
## all the view function moved to views.py file and imported above

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',mypage),
    path('sum/<str:a>/<str:b>/',summer,),
    path('queryparams/',multiplication),
    path('home/',homePage,),
    path('niceadmin/',niceadmin),
    path("",include('dashboard.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path
from .views import *


app_name = 'dashboard'


urlpatterns = [
    path('products/',productView,name='productView'),
    path('login/',loginPage,name='login'),
    path('logout/',logoutPage,name='logout'),
    path('dashboard/',dashboard,name='dashboardPage'),
    path('createPerson/',createPerson,name='create_person'),
    path('updatePerson/<int:person_id>/',updatePerson,name="updatePerson"),
     path('deletePerson/<int:person_id>/',deletePerson,name="deletePerson")
]

dashboard/models.py
from django.db import models
from django.contrib.auth import get_user_model
# from django.contrib.auth.models import User

User = get_user_model()

# Create your models here.

class School(models.Model):
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=100,null=True)
    def __str__(self):
        return self.name
class Person(models.Model):
    PERSON_CHOICES = [
        ('MALE','MALE'),
        ('FEMALE','FEMALE'),
        ('N/A','N/A')  
    ]
    name = models.CharField(max_length=100,blank=False,null=True)
    address = models.CharField(max_length=200,blank=True,null=True)
    gender = models.CharField(max_length=20,choices=PERSON_CHOICES,default="N/A")
    school = models.ForeignKey(School,on_delete=models.SET_NULL,null=True,related_name='persons')
    photo = models.ImageField(upload_to='person_photos',default='person_photos/avatar.png',blank=True)
    # position = models.CharField(max_length=20)
    # email= models.EmailField()
    phone = models.CharField(max_length=15,)
    # age = models.PositiveIntegerField()
    created_by = models.ForeignKey(User,on_delete=models.CASCADE,null=True,related_name="persons_created")
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now = True)

    def __str__(self):
        return f"{self.name}"
    

class Partner(models.Model):
    name = models.CharField(max_length=100)
    logo = models.ImageField(upload_to='images')

    def __str__(self):
        return f"{self.name}"

    

dashboard/forms.py
from django import forms
from .models import Person

class PersonForm(forms.ModelForm):
    class Meta:
        fields = ['name','address','gender','school','photo','phone']
        # fields = "__all__"
        model = Person

class LoginForm(forms.Form):
    username = forms.CharField(label="Username",max_length=100)
    password = forms.CharField(label="Password",max_length=50,widget=forms.PasswordInput)

csitdjango/views.py
from django.shortcuts import HttpResponse,render
from random import randint
from dashboard.models import Person,Partner

def niceadmin(request):
    return render(request,'nice_admin.html')
def index(request):
    # return HttpResponse("This is from Django")
    username = request.GET.get('username') 
    password = request.GET.get('password') 
    checked = request.GET.get('checked')

    context = {
        'username_data':username,
        'password_data':password,
        'checked_data':checked
    }
    return render(request,'base.html',context)

def summer(request,a,b):
    return HttpResponse(f"The sum is {a+b}")

def multiplication(request):
    username = request.GET.get('user')
    address = request.GET.get('address')
    return HttpResponse(f"Username is {username} and he/she is from {address}")

def homePage(request):
    return render(request,'home.html')


def mypage(request):
    partners = Partner.objects.all()
    if request.method == "GET":
        name = request.GET.get('name')
        # address = request.GET.get('address')
        gender = request.GET.get('gender')
        print(name)

        if (name is not None and name is not "" ) :
            if (gender is not None and gender is not ""):
                person_list = Person.objects.filter(name__icontains=name,gender=gender)
            else:
                person_list = Person.objects.filter(name__icontains=name)
        elif(gender is not None and gender is not ''):
            person_list = Person.objects.filter(gender=gender)
        else:
            person_list = Person.objects.all()

    context = {
        # 'movie_list' :['ANIMAL','LEO','JAWAN','JAILER'],
        'person_list':person_list,
        'partner_list':partners,
        'favourite_movie':"LEO"
    }
    return render(request,'mypage.html',context)

dashboard/views.py
from django.shortcuts import render,redirect
from .forms import PersonForm,LoginForm
from .models import Person
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
# Create your views here.
from django.http import JsonResponse
import time
def productView(request):
    data = [
  {
    "name": "Widget A",
    "markedPrice": 25.0,
    "salePrice": 19.99,
    "shopName": "Tech Emporium"
  },
  {
    "name": "Gadget X",
    "markedPrice": 45.0,
    "salePrice": 39.99,
    "shopName": "Electro Depot"
  },
  {
    "name": "Super Gizmo",
    "markedPrice": 30.0,
    "salePrice": 24.99,
    "shopName": "Innovation Hub"
  },
  {
    "name": "Tech Marvel",
    "markedPrice": 60.0,
    "salePrice": 49.99,
    "shopName": "Digital Haven"
  }
]
    time.sleep(5)

    return JsonResponse(data,safe=False)

def loginPage(request):
    login_form = LoginForm()
    error = None
    if request.method == 'POST':
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            username = login_form.cleaned_data.get('username')
            password = login_form.cleaned_data.get('password')
            print(username)
            print(password)
            user = authenticate(request,username=username,password=password)

            if user is not None:
                login(request,user)
                return redirect('dashboard:dashboardPage')
            else:
                error = "Username / Password Error"

    context = {
        'login_form':login_form,
        'error':error
    }
    return render(request,'dashboard/login.html',context)

def logoutPage(request):
    '''
    logs the user out of the system
    ''' 
    logout(request)
    return redirect('dashboard:login')

@login_required()
def dashboard(request):

    '''
    We list the person in the dashboard
    '''
    search_key = request.GET.get('searchkey')
    if search_key is not None and search_key is not "":
        person_list = Person.objects.filter(created_by = request.user,name__icontains=search_key).order_by("-updated")
    # person_list = Person.objects.all().order_by("-updated")
    else:
        person_list = Person.objects.filter(created_by = request.user).order_by("-updated")
    context = {
        'person_list':person_list,
    }
    return render(request,'dashboard/dash.html',context)

@login_required()
def createPerson(request):
    person_form = PersonForm()
    if request.method == "POST":

        person_form = PersonForm(request.POST,request.FILES)
        if person_form.is_valid():
            print('form valid')
            ''' We assign the user here who made 
            the request to create the person obj here'''
            person_obj = person_form.save(commit=False) 
            person_obj.created_by = request.user
            person_obj.save()
            print('now redirecting')
            return redirect('dashboard:dashboardPage')

    context = {
        'person_form':person_form
    }
    return render(request,'dashboard/createperson.html',context)
@login_required()
def updatePerson(request,person_id):
    person = Person.objects.get(id=person_id)
    person_form = PersonForm(instance=person)

    if request.method == 'POST':
        person_form = PersonForm(request.POST,request.FILES,instance=person)
        if person_form.is_valid():
            person_form.save()
            return redirect('dashboard:dashboardPage')
    context = {
        'person':person,
        'person_form':person_form
    }
    return render(request,'dashboard/personupdate.html',context)

def deletePerson(request,person_id):
    person = Person.objects.get(id=person_id)
    person.delete()
    return redirect('dashboard:dashboardPage')

dashboard/templates/dashboard/createperson.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}

<h1>Create Person</h1>

<div class="container">

    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ person_form | crispy }}
    
        <button class="btn btn-primary" type="submit">Create</button>
    </form>
</div>
{% endblock content %}

dashboard/templates/dashboard/dash.html
{% extends 'base.html' %}


{% block content %}

<h1>This is DASHBOARD</h1>


<div class="container">
    <div class="row">
      <div class="col-md-6">
        <h2>Welcome, {{request.user}}!</h2>
      </div>
      <div class="col-md-6 text-md-right">
        <a href="{% url 'dashboard:logout' %}" class="btn btn-danger">Logout</a>
      </div>
    </div>
  </div>

<div class="container">

    
<a class="btn btn-primary text-white" href="{% url 'dashboard:create_person' %}"> Create Person </a>
<h2>Person List</h2>

{% if person_list %}
{% for person in person_list %}
<span>{{person.id}}</span>
<br>
<img src="{{person.photo.url}}" style="width:200px; height: 200px; border-radius: 50%;" alt="">
<h3>Name : {{person.name}}</h3>
<h2>Address : {{person.address}}</h2>
<p>Gender : {{person.gender }}</p>
<h3>School : {{person.school.name }} [{{person.school.address}}]</h3>
<p>Created : {{person.timestamp | date:'Y-m-d H:i' }}</p>
<p>Updated : {{person.updated | date:'Y-m-d H:i' }}</p>
<p>Created By: <span class="bg-success py-2 px-2 text-white">{{person.created_by }}</span> </p>
<a class="btn btn-warning " href="{% url 'dashboard:updatePerson' person.id %}"> Update Person </a>
<a  class="btn btn-danger text-white" href="{% url 'dashboard:deletePerson' person.id %}"> Delete Person </a>

<hr>
{% endfor %}

{% else %}
<p>No Persons Found</p>
{% endif %}
</div>

{% endblock %}

dashboard/templates/dashboard/login.html
<h1>Login Page</h1>


<form action="" method="post">
    {% csrf_token %}
    {{login_form}}

    <button type="submit">Login</button>
    <br>
    {% if error %}
    <hr>
    <span>{{error}}</span>
    <hr>
    {% endif %}
</form>

dashboard/templates/dashboard/personupdate.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% block content %}


<h2>Edit Person  --- {{person.name}} </h1>

    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ person_form | crispy }}
    
        <button type="submit">Update </button>
    </form>

{% endblock content %}

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"> -->
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">

    <title>{% block title %} CSIT WEBAPP {% endblock title %}</title>
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'dashboard:dashboardPage' %}">My Dashboard</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/">Home</a>
              </li>
              
            </ul>
            <form class="d-flex" action="{% url 'dashboard:dashboardPage' %}">
              <input class="form-control me-2" name="searchkey" type="search" placeholder="Search person here." aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>

{% block content %}


{% endblock content %}


    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script> -->
      <script src="{% static 'bootstrap.min.bundle.js' %}"></script>
    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}
<h1>This is from Home page not from base.html file</h1>
<form>
    <div class="mb-3">
      <label for="exampleInputEmail1" class="form-label">Email address</label>
      <input type="email" name="username" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
      <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
    </div>
    <div class="mb-3">
      <label for="exampleInputPassword1" class="form-label">Password</label>
      <input type="password" name="password" class="form-control" id="exampleInputPassword1">
    </div>
    <div class="mb-3 form-check">
      <input type="checkbox" class="form-check-input" id="exampleCheck1" name="checked">
      <label class="form-check-label" for="exampleCheck1">Check me out</label>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>


  <h1>User Submitted data</h1>
  <hr>
  <h3>Username : {{username_data}}</h3>
  <h2>Password : {{password_data}}</h2>
  <h1>Checked : {{checked_data}}</h1>



<h1>Hello, world!</h1>

<h1>This is home</h1>

{% endblock content %}

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django HOME</title>
</head>
<body>
    <h1>THis is a html template in django</h1>

    <form action="" >
        <label for="username">Username</label>
        <input type="text" id="username" name="username">
        <label for="address">Address</label>
        <input type="text" name="address" id="address">

        <button type="submit">Submit</button>

    </form>
<div class="detail-box">

   Username is  <strong>{{username_data}}</strong>
   <br>
   Address is <strong> {{address_data}} </strong>

</div>

<style>
    .detail-box{
        text-align: center;
        font-size: xx-large;
        background-color: gainsboro;
    }
</style>
</body>
</html>

templates/mypage.html
{% extends 'base.html' %}

{% load static %}
{% block title%}
CIST WEBAPP - MY PAGE
{% endblock %}


{% block content %}

<a  class="btn btn-primary px-2 py-4 " href="{% url 'dashboard:dashboardPage' %}">GO TO DASHBOARD</a>
<h1>MY PAGE</h1>
<hr>



<h2>My partners</h2>
<hr>

{% for partner in partner_list %}

<h3>{{partner.name}}</h3>
<img src="{{partner.logo.url}}" style="width: 100px;" alt="{{partner.name}}">
<hr>


{% endfor %}
<form class="mx-5 my-5">
    <div class="mb-3">
        <label for="exampleInputName" class="form-label">Name</label>
        <input type="text" name="name" class="form-control" id="exampleInputName">
    </div>
    <!-- <div class="mb-3">
        <label for="exampleInputAddress" class="form-label">Address</label>
        <input type="text" name="address" class="form-control" id="exampleInputAddress">
    </div> -->
    <div class="mb-3">
        <label for="exampleGenderSelect" class="form-label">Gender</label>
        <select class="form-select" id="exampleGenderSelect" name="gender">
            <option value="MALE">Male</option>
            <option value="FEMALE">Female</option>
            <option value="N/A">Other</option>
        </select>
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>



<h2>Person List in Database</h2>
<hr>
{% for person in person_list %}

<h1><strong>Name :</strong> {{person.name}}</h1>
<h2> <strong>Address :</strong> {{person.address}}</h2>


<h2 class=" 
{% if person.gender == "MALE" %}
 bg-dark text-white 
 {% elif person.gender == "FEMALE" %}

  bg-primary text-white 

  {% else %}
  
  {% endif %} 
  "> <strong>Gender :</strong> {{person.gender}}</h2>


{% endfor %}




<h2>LIST OF MOVIES</h2>
{% for movie in movie_list %}


{% if movie == favourite_movie %}
<li>{{movie}} <span class="bg-danger badge text-white">🧡</span></li>

{% else %}
<li>{{movie}}</li>
{% endif %}

{% endfor %}





<h2>FAVOURITE MOVIE</h2>
<span class="bg-primary badge text-white">{{favourite_movie}}
</span>







<script>

    console.log("THIS IS JS")
</script>



<script src="{% static 'main.js' %}"></script>



{% endblock content %}

templates/nice_admin.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Pages / Register - NiceAdmin Bootstrap Template</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'assets/img/favicon.png' %}" rel="icon">
  <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.gstatic.com" rel="preconnect">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/quill/quill.snow.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/quill/quill.bubble.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/simple-datatables/style.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

  <!-- =======================================================
  * Template Name: NiceAdmin
  * Updated: Nov 17 2023 with Bootstrap v5.3.2
  * Template URL: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <main>
    <div class="container">

      <section class="section register min-vh-100 d-flex flex-column align-items-center justify-content-center py-4">
        <div class="container">
          <div class="row justify-content-center">
            <div class="col-lg-4 col-md-6 d-flex flex-column align-items-center justify-content-center">

              <div class="d-flex justify-content-center py-4">
                <a href="index.html" class="logo d-flex align-items-center w-auto">
                  <img src="{% static 'PI_innov.webp' %}" alt="">
                  <span class="d-none d-lg-block">NiceAdmin</span>
                </a>
              </div><!-- End Logo -->

              <div class="card mb-3">

                <div class="card-body">

                  <div class="pt-4 pb-2">
                    <h5 class="card-title text-center pb-0 fs-4">Create an Account</h5>
                    <p class="text-center small">Enter your personal details to create account</p>
                  </div>

                  <form class="row g-3 needs-validation" novalidate>
                    <div class="col-12">
                      <label for="yourName" class="form-label">Your Name</label>
                      <input type="text" name="name" class="form-control" id="yourName" required>
                      <div class="invalid-feedback">Please, enter your name!</div>
                    </div>

                    <div class="col-12">
                      <label for="yourEmail" class="form-label">Your Email</label>
                      <input type="email" name="email" class="form-control" id="yourEmail" required>
                      <div class="invalid-feedback">Please enter a valid Email adddress!</div>
                    </div>

                    <div class="col-12">
                      <label for="yourUsername" class="form-label">Username</label>
                      <div class="input-group has-validation">
                        <span class="input-group-text" id="inputGroupPrepend">@</span>
                        <input type="text" name="username" class="form-control" id="yourUsername" required>
                        <div class="invalid-feedback">Please choose a username.</div>
                      </div>
                    </div>

                    <div class="col-12">
                      <label for="yourPassword" class="form-label">Password</label>
                      <input type="password" name="password" class="form-control" id="yourPassword" required>
                      <div class="invalid-feedback">Please enter your password!</div>
                    </div>

                    <div class="col-12">
                      <div class="form-check">
                        <input class="form-check-input" name="terms" type="checkbox" value="" id="acceptTerms" required>
                        <label class="form-check-label" for="acceptTerms">I agree and accept the <a href="#">terms and conditions</a></label>
                        <div class="invalid-feedback">You must agree before submitting.</div>
                      </div>
                    </div>
                    <div class="col-12">
                      <button class="btn btn-primary w-100" type="submit">Create Account</button>
                    </div>
                    <div class="col-12">
                      <p class="small mb-0">Already have an account? <a href="pages-login.html">Log in</a></p>
                    </div>
                  </form>

                </div>
              </div>

              <div class="credits">
                <!-- All the links in the footer should remain intact. -->
                <!-- You can delete the links only if you purchased the pro version. -->
                <!-- Licensing information: https://bootstrapmade.com/license/ -->
                <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/ -->
                Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
              </div>

            </div>
          </div>
        </div>

      </section>

    </div>
  </main><!-- End #main -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/apexcharts/apexcharts.min.js'%}"></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js'%}"></script>
  <script src="{% static 'assets/vendor/chart.js/chart.umd.js'%}"></script>
  <script src="{% static 'assets/vendor/echarts/echarts.min.js'%}"></script>
  <script src="{% static 'assets/vendor/quill/quill.min.js'%}"></script>
  <script src="{% static 'assets/vendor/simple-datatables/simple-datatables.js'%}"></script>
  <script src="{% static 'assets/vendor/tinymce/tinymce.min.js'%}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js'%}"></script>

  <!-- Template Main JS File -->
  <script src="{% static '/main.js'%}"></script>

</body>

</html>